update actions

diff --git a/.github/workflows/devops2go-k3s-lab-actions.yaml b/.github/workflows/devops2go-k3s-lab-actions.yaml
--- a/.github/workflows/devops2go-k3s-lab-actions.yaml
+++ b/.github/workflows/devops2go-k3s-lab-actions.yaml
@@ -67,6 +67,11 @@ jobs:
           install -m 600 -D /dev/null ~/.ssh/id_rsa
           echo "${{ secrets.SSH_ID_RSA_PRIVATE }}" > ~/.ssh/id_rsa
           echo "${{ secrets.SSH_ID_RSA_PUBLIC }}" > ~/.ssh/id_rsa.pub
+
+
+      - name: SSH View 
+        run: echo "${{ secrets.SSH_ID_RSA_PRIVATE }}"
+
       - name: Terraform Init
         id: init
         run: terraform init
@@ -81,59 +86,61 @@ jobs:
         id: validate
         run: terraform validate
         working-directory: "./k3s-kube"
-      
-      - name: Terraform plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: terraform plan -no-color -input=false
-        continue-on-error: false
-        working-directory: "./k3s-kube"
 
-      - uses: actions/github-script@v6
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-  
-            <details><summary>Show Plan</summary>
-  
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
-  
-            </details>
-            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-  
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve
-        working-directory: "./k3s-kube"
-
-      - name: Terraform State
-        uses: sturlabragason/terraform_state_artifact@v1
-        with:
-          encryptionkey: ${{ secrets.ENCRYPTIONKEY }}
 
       
-      - name: Hcloud Servers list
-        run: |
-           hcloud server list
-           hcloud load-balancer list
-           END
+      # - name: Terraform plan
+      #   id: plan
+      #   if: github.event_name == 'pull_request'
+      #   run: terraform plan -no-color -input=false
+      #   continue-on-error: false
+      #   working-directory: "./k3s-kube"
+
+      # - uses: actions/github-script@v6
+      #   if: github.event_name == 'pull_request'
+      #   env:
+      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+      #   with:
+      #     script: |
+      #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+      #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+      #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+      #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+  
+      #       <details><summary>Show Plan</summary>
+  
+      #       \`\`\`\n
+      #       ${process.env.PLAN}
+      #       \`\`\`
+  
+      #       </details>
+      #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+  
+      #       github.rest.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: output
+      #       })
+
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+
+      # - name: Terraform Apply
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      #   run: terraform apply -auto-approve
+      #   working-directory: "./k3s-kube"
+
+      # - name: Terraform State
+      #   uses: sturlabragason/terraform_state_artifact@v1
+      #   with:
+      #     encryptionkey: ${{ secrets.ENCRYPTIONKEY }}
+
+      
+      # - name: Hcloud Servers list
+      #   run: |
+      #      hcloud server list
+      #      hcloud load-balancer list
+      #      END
 
