update actions

diff --git a/.github/workflows/devops2go-k3s-lab-actions.yaml b/.github/workflows/devops2go-k3s-lab-actions.yaml
--- a/.github/workflows/devops2go-k3s-lab-actions.yaml
+++ b/.github/workflows/devops2go-k3s-lab-actions.yaml
@@ -9,6 +9,10 @@ env:
   HCLOUD_TOKEN: ${{secrets.HCLOUD_TOKEN}}
   SSH_ID_RSA_PRIVATE: ${{secrets.SSH_ID_RSA_PRIVATE}}
   SSH_ID_RSA_PUBLIC: ${{secrets.SSH_ID_RSA_PUBLIC}}
+  TF_VAR_hcloud_token: ${{secrets.HCLOUD_TOKEN}}
+  CLOUDFLARE_API_KEY: ${{secrets.CLOUDFLARE_API_KEY}}
+  CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
+  working-directory: "./k3s-kube"
   
 
 jobs:
@@ -23,8 +27,13 @@ jobs:
       HCLOUD_TOKEN: ${{secrets.HCLOUD_TOKEN}}
     
     steps:
-      - name: Checkout Repo
+      - name: Get Code
         uses: actions/checkout@v3
+      # - name: Cache dependencies
+      #   uses: actions/cache@v3
+      #   with:
+      #     path: ~/.npm
+      #     key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
       
       - name: Terraform Installation
         uses: hashicorp/setup-terraform@v2
@@ -61,80 +70,81 @@ jobs:
           SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
           TF_VAR_hcloud_token: ${{ vars.HCLOUD_TOKEN }}
           HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
+      
 
 
       - name: Terraform Init
         id: init
         run: terraform init
         working-directory: "./k3s-kube"
+        env:
+          TF_VAR_hcloud_token: ${{secrets.HCLOUD_TOKEN}}
 
       - name: Terraform format
         id: fmt
         run: terraform fmt -check
         working-directory: "./k3s-kube"
+        env:
+          TF_VAR_hcloud_token: ${{secrets.HCLOUD_TOKEN}}
       
       - name: Terraform validate
         id: validate
         run: terraform validate
         working-directory: "./k3s-kube"
 
+      - name: Upload Artfacts
+        uses: actions/upload-artfact@v3
+        with:
+          name: terraform
+          path: |
+            ../.terraform
+            ./k3s-kube/.terraform.lock.hcl
+            ~/.ssh
+
+
 
       
-      - name: Terraform plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: terraform plan -no-color -input=false
-        continue-on-error: false
-        working-directory: "./k3s-kube"
+      # - name: Terraform plan
+      #   id: plan
+      #   if: github.event_name == 'pull_request'
+      #   run: terraform plan -no-color -input=false
+      #   continue-on-error: false
+      #   working-directory: "./k3s-kube"
 
-      - uses: actions/github-script@v6
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+      # - uses: actions/github-script@v6
+      #   if: github.event_name == 'pull_request'
+      #   env:
+      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+      #   with:
+      #     script: |
+      #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+      #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+      #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+      #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
   
-            <details><summary>Show Plan</summary>
+      #       <details><summary>Show Plan</summary>
   
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
+      #       \`\`\`\n
+      #       ${process.env.PLAN}
+      #       \`\`\`
   
-            </details>
-            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+      #       </details>
+      #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
   
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
+      #       github.rest.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: output
+      #       })
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve
-        working-directory: "./k3s-kube"
-        env:
-            SSH_ID_RSA_PRIVATE: ${{secrets.SSH_ID_RSA_PRIVATE}}
-            SSH_ID_RSA_PUBLIC: ${{secrets.SSH_ID_RSA_PUBLIC}}
+      # - name: Terraform Apply
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      #   run: terraform apply -auto-approve
+      #   working-directory: "./k3s-kube"
 
-      - name: Terraform State
-        uses: sturlabragason/terraform_state_artifact@v1
-        with:
-          encryptionkey: ${{ secrets.ENCRYPTIONKEY }}
-
-      
-      - name: Hcloud Servers list
-        run: |
-           hcloud server list
-           hcloud load-balancer list
-           END
 
